spring:
  profiles:
    active:
      - loglocal
      - mongolocal
  jwt:
    secret-key: portpolio
    expire-time: 36000000
    header-key: X-AUTH-TOKEN

spring.main.allow-bean-definition-overriding: true
---
spring:
  profiles: mongolocal

  data:
    mongodb:
      authentication-database: admin
      #uri: mongodb://localhost:27017/firestock
      uri: mongodb://firestockapi:firestockpwd@54.180.28.73:27017/firestock?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
---
spring:

server:
  port: 8080

  tomcat:
    accesslog:
      enabled: true
      prefix: access_log_firestockapi
      pattern: "[%A] [%v] [%{yyyy-MM-dd HH:mm:ss}t]  [%a] [%h] [%S] [accesslog] [%m] [%r] [%{User-Agent}i]"
    #basedir: /Users/kimjimin/logs
    basedir: /logs/
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: firestock
    key-store-type: PKCS12
    key-alias: bns-ssl

security:
  require-ssl=true


---
upbit :
  key :
    AccessKey :
    SecretKey :
  address:
    market: https://api.upbit.com/v1/market/all?isDetails=false
    minuteCandle: https://api.upbit.com/v1/candles/minutes
    orderbook: https://api.upbit.com/v1/orderbook
    accounts: https://api.upbit.com/v1/accounts

binance :
  key:
  address:
    market: https://api.binance.com/api/v3/ticker/price